### ISSUE TITLE
Extra item in resulting Array

### ISSUE THREAD

**Issue by markandrus** [es-shims/Array.prototype.flatMap#1]
Hi, I was testing this out and I noticed an extra item is included in the resulting Array:

```
$ node -v
v8.6.0
$ npm install array.prototype.flatmap
+ array.prototype.flatmap@1.1.0
$ node -e "console.log(require('array.prototype.flatmap')([1, 2, 3], a => [a]))"
[ 1, 2, 3, <1 empty item> ]
```

**Comment by ljharb** [comment]
Thanks! This has helped me find a likely issue in the actual spec text. I'll get a fix published for this (and for the `flatten` polyfill) tomorrow!

**Comment by ljharb** [comment]
Thanks, fixed in the spec in https://github.com/tc39/proposal-flatMap/pull/47
